# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: auth_postgres1
    environment:
      POSTGRES_DB: authentication_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5400:5400"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - redApp

  python:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - redApp

volumes:
  postgres_data:

networks:
  redApp:
    driver: bridge